import './globals.css';
import Header from './Header';
import { Inter } from 'next/font/google';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={inter.className}>
      <body className="background-gradient">
        <Header className="px-[112px] pt-[22.2px]" />
        <div className="mt-[124px] pl-[112px] pr-[82px] mb-28">{children}</div>
      </body>
    </html>
  );
}
